import { existsSync } from 'node:fs';
import type { AssetResolver } from '../asset-resolution/asset-resolver';
import type { Logger } from '../logger';
import type { SourceFileChangeTracker } from './source-file-change-tracker';
import type { TsDefinitionEmitter } from './ts-definition-emitter';
import { IdempotentFileWriter } from './idempotent-file-writer';
import { NodeModulesLocator } from './node-modules-locator';
import { PackageCollisionChecker, type CollisionSentinelFile } from './package-collision-checker';
import { ShimPackage } from './shim-package';
import { FileDiscoverer, type DiscoveryGroup } from './file-discoverer';

const TYPESHIM_SENTINEL: CollisionSentinelFile = {
  name: '.dotnet-wasm-typeshim',
  content: 'Generated by unplugin-dotnet-wasm. Provides editor and tsc types for virtual .NET WASM imports.\n',
};

/**
 * Generates "magic" type-only packages under the consumer's `node_modules` so
 * tsserver/`tsc` resolve the plugin's virtual imports with full types.
 */
export class ShimPackageGenerator {
  private locator: NodeModulesLocator;
  private writer: IdempotentFileWriter;
  private collisionChecker: PackageCollisionChecker;
  private discoverer: FileDiscoverer;

  constructor(
    root: string,
    resolver: AssetResolver,
    private readonly changeTracker: SourceFileChangeTracker,
    private readonly emitter: TsDefinitionEmitter,
    private readonly logger: Logger,
  ) {
    this.locator = new NodeModulesLocator(root);
    this.writer = new IdempotentFileWriter();
    this.collisionChecker = new PackageCollisionChecker(this.writer, TYPESHIM_SENTINEL);
    this.discoverer = new FileDiscoverer(resolver, logger);
  }

  /** Idempotent: safe to call on every build. */
  async generate(): Promise<void> {
    const groups = this.discoverer.discover();
    if (groups.length === 0) return;

    for (const group of groups) {
      await this.writePackage(group);
    }
  }

  private async writePackage(group: DiscoveryGroup): Promise<void> {
    const pkg = new ShimPackage(this.locator, group.packageName);
    try {
      if (await this.collision(pkg, group)) return;

      for (const entry of group.entries.filter(e => e.sourceFile || e.definitionFile)) {
        const chosenFile = entry.definitionFile ?? entry.sourceFile;
        if (!chosenFile) continue;

        const { relFile, absFile } = pkg.fileFor(entry.subpath);
        const changed = await this.changeTracker.hasChanged(chosenFile);
        if (!changed && existsSync(absFile)) {
          // Ensure package.json stays complete.
          pkg.addExport(entry.subpath, relFile);
          continue;
        }

        const dts = entry.definitionFile ? this.emitter.reExport(entry.definitionFile)
          : entry.sourceFile ? this.emitter.compile(entry.sourceFile)
          : null;
        if (dts === null) continue;

        await this.writer.write(absFile, dts);
        pkg.addExport(entry.subpath, relFile);
      }
      const manifest = pkg.emitPackageJson();
      if (manifest === null) return;
      await this.writer.write(manifest.path, manifest.json);
    } catch (err) {
      this.logger.warn(`type-shims: write failed for "${group.packageName}" (${String(err)}); skipping`);
    }
  }

  private async collision(pkg: ShimPackage, group: DiscoveryGroup): Promise<boolean> {
    if (!(await this.collisionChecker.ensureCollisionFree(pkg.dir))) {
        const conflictingFiles = group.entries
          .flatMap(e => [e.sourceFile, e.definitionFile].filter((f): f is string => Boolean(f)))
          .join(', ');
        this.logger.warn(`"${group.packageName}" already exists in node_modules. Skipping to avoid corrupting it. To resolve this, rename your source file or its path to not start with "${group.packageName}". Conflicting files: [${conflictingFiles}].`);
        return true;
      }
      return false;
  }
}
