import { existsSync } from 'node:fs';
import type { Logger } from '../logger';
import type { SourceFileChangeTracker } from './source-file-change-tracker';
import type { TsDefinitionEmitter } from './ts-definition-emitter';
import { IdempotentFileWriter } from './idempotent-file-writer';
import type { NodeModulesLocator } from './node-modules-locator';
import { PackageCollisionChecker, type CollisionSentinelFile } from './package-collision-checker';
import { ShimPackage } from './shim-package';
import type { FileDiscoverer, DiscoveryGroup } from './file-discoverer';

const TYPESHIM_SENTINEL: CollisionSentinelFile = {
  name: '.dotnet-wasm-typeshim',
  content: 'Generated by unplugin-dotnet-wasm. Provides editor and tsc types for virtual .NET WASM imports.\n',
};

interface PlannedEntry {
  subpath: string;
  relFile: string;
  absFile: string;
  dts?: string;
}

/**
 * Generates "magic" type-only packages under the consumer's `node_modules` so
 * tsserver/`tsc` resolve the plugin's virtual imports with full types.
 */
export class ShimPackageGenerator {
  private readonly writer = new IdempotentFileWriter();
  private readonly collisionChecker = new PackageCollisionChecker(this.writer, TYPESHIM_SENTINEL);

  constructor(
    private readonly locator: NodeModulesLocator,
    private readonly discoverer: FileDiscoverer,
    private readonly changeTracker: SourceFileChangeTracker,
    private readonly emitter: TsDefinitionEmitter,
    private readonly logger: Logger,
  ) {}

  /** Idempotent: safe to call on every build. */
  async generate(): Promise<void> {
    const groups = this.discoverer.discover();
    if (groups.length === 0) return;

    for (const group of groups) {
      await this.writePackage(group);
    }
  }

  private async writePackage(group: DiscoveryGroup): Promise<void> {
    const pkg = new ShimPackage(this.locator, group.packageName);
    try {
      const planned = await this.planPackageEntries(pkg, group);

      if (planned.length === 0) return;
      if (await this.collision(pkg, group)) return;

      for (const item of planned) {
        if (item.dts !== undefined) {
          await this.writer.write(item.absFile, item.dts);
        }
        pkg.addExport(item.subpath, item.relFile);
      }
      const manifest = pkg.emitPackageJson();
      if (manifest !== null) {
        await this.writer.write(manifest.path, manifest.json);
      }
    } catch (err) {
      this.logger.warn(`write failed for "${group.packageName}" (${String(err)}); skipping`);
    }
  }

  private async planPackageEntries(pkg: ShimPackage, group: DiscoveryGroup): Promise<PlannedEntry[]> {
    const planned: PlannedEntry[] = [];
    for (const entry of group.entries) {
      const chosenFile = entry.definitionFile ?? entry.sourceFile;
      if (!chosenFile) continue;

      const { relFile, absFile } = pkg.fileFor(entry.subpath);
      const changed = await this.changeTracker.hasChanged(chosenFile);
      if (!changed && existsSync(absFile)) {
        planned.push({ subpath: entry.subpath, relFile, absFile });
        continue;
      }

      const dts = entry.definitionFile
        ? this.emitter.forwardDTS(entry.definitionFile)
        : this.emitter.compileToDTS(entry.sourceFile!);
      if (dts === null) continue;
      planned.push({ subpath: entry.subpath, relFile, absFile, dts });
    }
    return planned;
  }

  private async collision(pkg: ShimPackage, group: DiscoveryGroup): Promise<boolean> {
    if (!(await this.collisionChecker.ensureCollisionFree(pkg.dir))) {
        const conflictingFiles = group.entries
          .flatMap(e => [e.sourceFile, e.definitionFile].filter((f): f is string => Boolean(f)))
          .join(', ');
        this.logger.warn(`"${group.packageName}" already exists in node_modules. Skipping to avoid corrupting it. To resolve this, rename your source file or its path to not start with "${group.packageName}". Conflicting files: [${conflictingFiles}].`);
        return true;
      }
      return false;
  }
}
