import { describe, it, expect, vi } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { AssetResolver } from '../asset-resolution/asset-resolver';
import type { SourceFileChangeTracker } from './source-file-change-tracker';
import type { TsDefinitionEmitter } from './ts-definition-emitter';
import type { Logger } from '../logger';
import { ShimPackageGenerator } from './shim-package-generator';

function createLogger(): Logger {
  return { error: vi.fn(), warn: vi.fn(), info: vi.fn(), debug: vi.fn() };
}

/** Fake resolver: `routes()` yields the given routes; `resolve()` maps them (missing → null). */
function createResolver(
  routes: string[],
  resolveMap: Record<string, string | null>,
): AssetResolver {
  return {
    routes: () => routes[Symbol.iterator](),
    resolve: (route: string) => (route in resolveMap ? resolveMap[route] : null),
  } as unknown as AssetResolver;
}

function createTracker(changed: boolean): SourceFileChangeTracker {
  return { hasChanged: vi.fn(async () => changed) } as unknown as SourceFileChangeTracker;
}

function createEmitter(
  reExportImpl?: (defFile: string) => string,
  compileImpl?: (sourceFile: string) => string | null,
): TsDefinitionEmitter & { reExport: ReturnType<typeof vi.fn>; compile: ReturnType<typeof vi.fn> } {
  return {
    reExport: vi.fn(reExportImpl || ((defFile) => `export * from '${defFile.slice(0, -5)}';\n`)),
    compile: vi.fn(compileImpl || (() => '// compiled\n')),
  } as unknown as TsDefinitionEmitter & {
    reExport: ReturnType<typeof vi.fn>;
    compile: ReturnType<typeof vi.fn>;
  };
}

/** A temp root and its (not-yet-created) node_modules dir — where the generator writes. */
function tempRoot(): { root: string; nm: string } {
  const root = mkdtempSync(join(tmpdir(), 'gen-'));
  return { root, nm: join(root, 'node_modules') };
}

describe('ShimPackageGenerator.generate', () => {
  it('filters non-TS/unresolvable routes and groups the rest by package', async () => {
    const { root, nm } = tempRoot();
    const resolver = createResolver(
      ['typeshim.ts', '_framework/dotnet.d.ts', 'app.css', 'orphan.ts'],
      {
        'typeshim.ts': '/src/typeshim.ts',
        '_framework/dotnet.d.ts': '/src/dotnet.d.ts',
        'app.css': '/src/app.css',
        'orphan.ts': null, // resolves to nothing → skipped
      },
    );
    const emitter = createEmitter(
      (defFile) => {
        // Strip declaration extension like real reExport does
        return `export * from '${defFile.slice(0, -5)}';\n`;
      },
      (sourceFile) => `// compiled:${sourceFile}\n`,
    );
    const generator = new ShimPackageGenerator(
      root,
      resolver,
      createTracker(true),
      emitter,
      createLogger(),
    );

    await generator.generate();

    // typeshim package (root entrypoint, source file)
    expect(readFileSync(join(nm, 'typeshim', 'index.d.ts'), 'utf8')).toBe('// compiled:/src/typeshim.ts\n');
    const typeshimPkg = JSON.parse(readFileSync(join(nm, 'typeshim', 'package.json'), 'utf8'));
    expect(typeshimPkg.exports).toEqual({ '.': { types: './index.d.ts' } });

    // _framework package (subpath entrypoint, definition file)
    expect(readFileSync(join(nm, '_framework', 'dotnet', 'index.d.ts'), 'utf8')).toBe(
      "export * from '/src/dotnet';\n",
    );
    const frameworkPkg = JSON.parse(readFileSync(join(nm, '_framework', 'package.json'), 'utf8'));
    expect(frameworkPkg.exports).toEqual({ './dotnet': { types: './dotnet/index.d.ts' } });

    // Non-TS route and the unresolvable route produced no packages.
    expect(existsSync(join(nm, 'app'))).toBe(false);
    expect(existsSync(join(nm, 'orphan'))).toBe(false);
  });

  it('skips emit for unchanged existing files but keeps the export', async () => {
    const { root, nm } = tempRoot();
    // Pre-existing generated file on disk (marked as ours with the sentinel).
    mkdirSync(join(nm, 'typeshim'), { recursive: true });
    writeFileSync(join(nm, 'typeshim', '.dotnet-wasm-typeshim'), '# Generated by unplugin-dotnet-wasm — provides editor and tsc types for virtual .NET WASM imports.\n');
    writeFileSync(join(nm, 'typeshim', 'index.d.ts'), '// stale but valid\n');

    const emitter = createEmitter(undefined, () => '// freshly compiled\n');
    const generator = new ShimPackageGenerator(
      root,
      createResolver(['typeshim.ts'], { 'typeshim.ts': '/src/typeshim.ts' }),
      createTracker(false), // unchanged
      emitter,
      createLogger(),
    );

    await generator.generate();

    expect(emitter.compile).not.toHaveBeenCalled();
    // File left untouched...
    expect(readFileSync(join(nm, 'typeshim', 'index.d.ts'), 'utf8')).toBe('// stale but valid\n');
    // ...but the export is still recorded in the manifest.
    const pkg = JSON.parse(readFileSync(join(nm, 'typeshim', 'package.json'), 'utf8'));
    expect(pkg.exports).toEqual({ '.': { types: './index.d.ts' } });
  });

  it('skips an entry whose compile returns null and writes no manifest for an empty package', async () => {
    const { root, nm } = tempRoot();
    const generator = new ShimPackageGenerator(
      root,
      createResolver(['typeshim.ts'], { 'typeshim.ts': '/src/typeshim.ts' }),
      createTracker(true),
      createEmitter(undefined, () => null), // compile returns null
      createLogger(),
    );

    await generator.generate();

    expect(existsSync(join(nm, 'typeshim', 'index.d.ts'))).toBe(false);
    expect(existsSync(join(nm, 'typeshim', 'package.json'))).toBe(false);
    expect(existsSync(join(nm, 'typeshim'))).toBe(false);
    expect(existsSync(join(nm, 'typeshim', '.dotnet-wasm-typeshim'))).toBe(false);
  });

  it('catches a throwing collaborator and warns instead of rejecting', async () => {
    const { root } = tempRoot();
    const logger = createLogger();
    const emitter = createEmitter(
      undefined,
      () => {
        throw new Error('boom');
      },
    );
    const generator = new ShimPackageGenerator(
      root,
      createResolver(['typeshim.ts'], { 'typeshim.ts': '/src/typeshim.ts' }),
      createTracker(true),
      emitter,
      logger,
    );

    await expect(generator.generate()).resolves.toBeUndefined();
    expect(logger.warn).toHaveBeenCalledOnce();
    expect(logger.warn).toHaveBeenCalledWith(expect.stringContaining('typeshim'));
  });

  it('detects foreign package and leaves it untouched, warns instead of clobbering', async () => {
    const { root, nm } = tempRoot();
    // Pre-seed with a foreign package (no sentinel).
    mkdirSync(join(nm, 'typeshim'), { recursive: true });
    const pkgJsonPath = join(nm, 'typeshim', 'package.json');
    const pkgJsonContent = '{"name":"typeshim","version":"9.9.9"}\n';
    writeFileSync(pkgJsonPath, pkgJsonContent);
    const dummyPath = join(nm, 'typeshim', 'dummy.js');
    const dummyContent = 'module.exports = {};\n';
    writeFileSync(dummyPath, dummyContent);

    const logger = createLogger();
    const generator = new ShimPackageGenerator(
      root,
      createResolver(['typeshim.ts'], { 'typeshim.ts': '/src/typeshim.ts' }),
      createTracker(true),
      createEmitter(undefined, () => '// generated\n'),
      logger,
    );

    await generator.generate();

    // Foreign files left byte-identical.
    expect(readFileSync(pkgJsonPath, 'utf8')).toBe(pkgJsonContent);
    expect(readFileSync(dummyPath, 'utf8')).toBe(dummyContent);
    // No generated files written.
    expect(existsSync(join(nm, 'typeshim', 'index.d.ts'))).toBe(false);
    // Collision warning issued.
    expect(logger.warn).toHaveBeenCalledWith(expect.stringContaining('already exists'));
  });

  it('prefers definition file over source file when both exist', async () => {
    const { root, nm } = tempRoot();
    const resolver = createResolver(
      ['pkg/foo.ts', 'pkg/foo.d.ts'],
      { 'pkg/foo.ts': '/src/foo.ts', 'pkg/foo.d.ts': '/src/foo.d.ts' },
    );
    const emitter = createEmitter((defFile) => `export * from '${defFile.slice(0, -5)}';\n`);
    const generator = new ShimPackageGenerator(
      root,
      resolver,
      createTracker(true),
      emitter,
      createLogger(),
    );

    await generator.generate();

    // Should have called reExport with the definition file path
    expect(emitter.reExport).toHaveBeenCalledOnce();
    const reExportCall = (emitter.reExport as ReturnType<typeof vi.fn>).mock.calls[0]![0];
    expect(reExportCall).toBe('/src/foo.d.ts');
    expect(emitter.compile).not.toHaveBeenCalled();
    // File should contain the re-export
    expect(readFileSync(join(nm, 'pkg', 'foo', 'index.d.ts'), 'utf8')).toContain('export * from');
  });
});
